export const Problem = {
  id: String,
  title: String,
  difficulty: String,
  category: String,
  order: Number,
  videoId: String,
};

export const problems = [
  {
    id: "two-sum",
    title: "Two Sum",
    difficulty: "Medium",
    category: "Array",
    order: 1,
    videoId: "DhFh8Kw7ymk",
  },
  {
    id: "flatted-linked-list",
    title: "Flattening a Linked List",
    difficulty: "Medium",
    category: "Linked List",
    order: 2,
    videoId: "ykelywHJWLg",
  },
  {
    id: "jump-game",
    title: "Binary Search Tree Iterator",
    difficulty: "Hard",
    category: "Binary Tree",
    order: 3,
    videoId: "D2jMcmxU4bs",
  },
  {
    id: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "Easy",
    category: "Stack",
    order: 4,
    videoId: "wkDfsKijrZ8",
  },
  {
    id: "search-a-2d-matrix",
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    category: "Binary Search",
    order: 5,
    videoId: "JXU4Akft7yk",
  },
  {
    id: "container-with-most-water",
    title: "Container With Most Water",
    difficulty: "Medium",
    category: "Two Pointers",
    order: 6,
    videoId: "e0kiAdtRGk8",
  },
  {
    id: "merge-intervals",
    title: "Merge Intervals",
    difficulty: "Medium",
    category: "intervals",
    order: 7,
    videoId: "IexN60k62jo",
  },
  {
    id: "maximum-depth-of-binary-tree",
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    category: "Tree",
    order: 8,
    videoId: "hyAqgckHUiA",
  },
  {
    id: "best-time-to-buy-and-sell-stock",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    category: "Array",
    order: 9,
    videoId: "34WE6kwq49U",
  },
  {
    id: "subsets",
    title: "Subsets",
    difficulty: "Medium",
    category: "Backtracking",
    order: 10,
    videoId: "iqKwK_o93Gw",
  },
];
